name: GenTx
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate-gentx:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17.1
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Display go version
        run: go version
      - name: Validate GenTx
        run: |
          bash -x ./scripts/validate-gentx.sh